title: Jose Luis Garcia Tucci
logo: https://github.com/jlgarciatucci/resume/assets/98712473/62705f4c-f711-45bc-a9c9-4377ae7d32cc.png
#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal
