title: Jose Luis Garcia Tucci
logo: https://github.com/jlgarciatucci/jlgarciatucci.io/assets/98712473/bb311bc4-86b6-42b6-b114-e4a5ead9edba.png
#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal
